version: 3
formats: all

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

python:
  # Install our python package before building the docs
  install:
   # - requirements: requirements.txt
    - method: pip
      path: .

conda:
  environment: docs/environment.yml

formats:
  - pdf