channels:
  - conda-forge
dependencies:
  - python>=3
  - pandoc
  - ipykernel
  - pip
  - pip:
    - nbsphinx
    - sphinx-book-theme
    - sphinx_mdinclude
    - torch==1.12.0
    - torchvision==0.13.0
    - munch==2.5.0
    - marshmallow==3.17.0
    - click==8.1.3
    - tifffile==2022.5.4
    - lmdb==1.3.0
    - zipp==3.8.0
    - numpy==1.23.0
    - pandas==1.4.3
    - h5py==3.2.0
    - dill==0.3.5.1
    - arff==0.9
    - matplotlib==3.5.2
    - tensorboard==2.13.0
    - tqdm==4.64.0
    - seaborn==0.11.2
    - albumentations==0.4.3
    - opencv-python==4.6.0.66
    - scikit-learn==1.1.1
    - scikit-image==0.18.3
    - scikit-multilearn==0.2.0
    - pytorch-ignite==0.4.9
    - faiss-cpu==1.7.2
    - timm==0.4.12